CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS grados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alumnos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grado_id INT NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (grado_id) REFERENCES grados(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS restricciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grado_id INT NOT NULL,
  batch_id VARCHAR(36) NOT NULL,
  alumno_id_1 INT NOT NULL,
  alumno_id_2 INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (grado_id) REFERENCES grados(id) ON DELETE CASCADE,
  FOREIGN KEY (alumno_id_1) REFERENCES alumnos(id) ON DELETE CASCADE,
  FOREIGN KEY (alumno_id_2) REFERENCES alumnos(id) ON DELETE CASCADE,
  UNIQUE KEY unique_pair (grado_id, alumno_id_1, alumno_id_2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
